NOT( (15 MOD 4) + 2 == 5 ) OR ( 10 * 2 > 15 AND NOT(8 / 4 <= 1) ) 
NOT(  3     + 2 ==5)  OR (  20  > 15 ) AND NOT( 2<=1) 
NOT(    VERDADERO     ) OR (    VERDADERO ) AND NOT ( FALSO)
(       FALSO      ) OR (    VERDADERO) AND  (VERDADERO)
VERDADERO AND VERDADERO = VERDADERO
FALSO OR VERDADERO = VERDADERO